twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_version: '%env(APP_VERSION)%'
        app_release: '%env(APP_RELEASE)%'

when@test:
    twig:
        strict_variables: true
